---
title: "Introduction to SpatialQC"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to SpatialTouchstone}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
pkgdown:
  as_is: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
library(SpatialQC)
```


## Xenium as an example 

### Read Data 


```{r expMat}
expMat ="~/Documents/GitHub/SpatialQM/datasets/Xenium/TOUCHSTONE_UOA_XR_FFPE_BR_1_SYD_C_R1/cell_feature_matrix/"
```

```{r read data }
# Do not return a seurat object 
result <- readSpatial(sample_id = "Xenium_test1",path="/Users/yliu08/Documents/GitHub/SpatialQM/datasets/Xenium/TOUCHSTONE_UOA_XR_FFPE_BR_1_SYD_C_R1",platform = "Xenium",seurat = FALSE)
head(result$Xenium_test1$TxMatrix[1:3])
```


It can return a `Seurat` Object by setting the `seurat=TRUE` with all required files by `Seurat`

```{r read data as a seurat object,warning=FALSE}
# Return a seurat object 
# result_seu <- readSpatial(sample_id = "Xenium_test1",path="/Users/yliu08/Documents/GitHub/SpatialQM/datasets/Xenium/TOUCHSTONE_UOA_XR_FFPE_BR_1_SYD_C_R1/",platform = "Xenium",seurat = TRUE)
# print(result_seu)
```
## QC 

We have mutliple QC functions, when using seurat object as the input, it will return a dataframe which can be used to generate plot using our plot functions.


```{r getTxPerCell1}
getTxPerCell<- getTxPerCell(expMat="/Users/yliu08/Documents/GitHub/SpatialQM/datasets/Xenium/TOUCHSTONE_UOA_XR_FFPE_BR_1_SYD_C_R1/",platform = "Xenium",seu_obj = NULL)
getTxPerCell
```

```{r getTxPerArea}
getTxPerArea <- getTxPerArea(cellSegMeta="/Users/yliu08/Documents/GitHub/SpatialQM/datasets/Xenium/TOUCHSTONE_UOA_XR_FFPE_BR_1_SYD_C_R1/cells.csv.gz",platform = "Xenium",seu_obj = NULL)
getTxPerArea
```
```{r getNcells}
getNcells<- getNcells(expMat=expMat,platform = "Xenium",seu_obj = NULL)
getNcells
```

```{r getGlobalFDR}
 getGlobalFDR<- getGlobalFDR(tx_file = "/Users/yliu08/Documents/GitHub/SpatialQM/datasets/Xenium/TOUCHSTONE_UOA_XR_FFPE_BR_1_SYD_C_R1/transcripts.csv.gz",platform = "Xenium",seu_obj = NULL)
getGlobalFDR
```


```{r getTxPerCell2}
getTxPerCell<- getTxPerCell(platform = "Xenium",seu_obj = NULL,expMat=expMat)
getTxPerCell
```

## To generate a QC report 

It will automatically generate a pdf qc report 


```{r gerante a QC report}

# genereateQCreport_table_1<- genereateQCreport_table(seu_obj = result_seu)
# genereateQCreport_table_1
#   sample_id platform ncell entropy_value sparsity_value tx_perarea tx_percell cell_tx_fraction mean_ratio max_ratio
# 1     test1   Xenium 80939         0.497          0.936  0.8983494   63.88845        0.7115717   2.306417  4.290015
```


